-- Libraries
local L = LibStub("AceLocale-3.0"):NewLocale("ConspicuousSpirits", "deDE", false)
if not L then return end


-- Translations
L["Conspicuous Spirits locked!"] = "Conspicuous Spirits entsperrt!"
L["Conspicuous Spirits unlocked!"] = "Conspicuous Spirits gesperrt!"
L["Color 1"] = "Farbe 1"
L["Color 2"] = "Farbe 2"
L["Color 3"] = "Farbe 3"
L["Complex"] = "Komplex"
L["Complex Display"] = "Komplexe Anzeige"
L["Conspicuous Spirits reset!"] = "Conspicuous Spirits zur\195\188ckgesetzt!"
L["Display"] = "Anzeige"
L["Display Type"] = "Anzeige-Art"
L["File to play."] = "Sound-Datei"
L["Font Size"] = "Schriftgr\195\182\195\159e"
L["Height"] = "H\195\182he"
L["Left mouse button to drag."] = "Linke Maustaste zum Ziehen."
L["Not possible to unlock in WeakAuras mode!"] = "Entsperren nicht m\195\182glich im WeakAuras-Modus!"
L["Open Configuration Window"] = "Einstellungsfenster \195\182ffnen"
L["Play Warning Sound when about to cap Shadow Orbs."] = "Warnton abspielen bei zu vielen Schattenkugeln."
L["Position"] = "Position"
L["Reset"] = "Zur\195\188cksetzen"
L["Reset Position"] = "Position zur\195\188cksetzen"
L["Reset to Defaults"] = "Einstellungen zur\195\188cksetzen"
L["Scale"] = "Gr\195\182\195\159e"
L["Set Frame Scale"] = "Rahmengr\195\182\195\159e einstellen"
L["Set Color 1"] = "Farbe 1 einstellen"
L["Set Color 2"] = "Farbe 2 einstellen"
L["Set Color 3"] = "Farbe 3 einstellen"
L["Set Font Size"] = "Schriftgr\195\182\195\159e einstellen"
L["Set Frame Height"] = "Rahmenh\195\182he einstellen"
L["Set Frame Width"] = "Rahmenbreite einstellen"
L["Set Number Spacing"] = "Zahlenabstand einstellen"
L["Set Shadow Orb Height"] = "Schattenkugelh\195\182he einstellen"
L["Set Shadow Orb Spacing"] = "Schattenkugelabstand einstellen"
L["Set Shadow Orb Width"] = "Schattenkugelbreite einstellen"
L["Show Orbs out of combat"] = "Schattenkugeln au\195\159erhalb des Kampfes anzeigen"
L["Shows the frame and toggles it for repositioning."] = "Macht den Rahmen sichtbar und verschiebbar"
L["Simple"] = "Einfach"
L["Simple Display"] = "Einfache Anzeige"
L["Sound"] = "Ton"
L["Spacing"] = "Abstand"
L["Toggle Lock"] = "Sperre ein-/ausschalten"
L["Warning Sound"] = "Warnton"
L["WeakAuras"] = "WeakAuras"
L["WeakAuras String"] = "WeakAuras-String"
L["WeakAuras String to use when \"WeakAuras\" Display is selected. Copy & paste into WeakAuras to import."] = "WeakAuras-String f\195\188r die \"WeakAuras\"-Anzeige. Zum Importieren ausschneiden & in WeakAuras einf\195\188gen."
L["Width"] = "Breite"
L["Will show Shadow Orbs frame even when not in combat."] = "Schattenkugeln anzeigen wenn man sich nicht im Kampf befindet."