-- Libraries
local L = LibStub("AceLocale-3.0"):NewLocale("ConspicuousSpirits", "enUS", true)
if not L then return end


-- Translations
L["Aggressive Caching"] = true
L["Aggressive Caching Interval"] = true
L["Conspicuous Spirits locked!"] = true
L["Conspicuous Spirits unlocked!"] = true
L["Color 1"] = true
L["Color 2"] = true
L["Color 3"] = true
L["Complex"] = true
L["Complex Display"] = true
L["Conspicuous Spirits reset!"] = true
L["Display"] = true
L["Display Type"] = true
L["Enables frequent distance scanning of all available targets. Will increase CPU usage slightly and is only going to increase accuracy in situations with many fast-moving mobs."] = true
L["File to play."] = true
L["Font"] = true
L["Font Size"] = true
L["General"] = true
L["Height"] = true
L["IronMaidensShipMessage"] = "prepares to man the Dreadnaught's Main Cannon!"
L["Left mouse button to drag."] = true
L["Not possible to unlock in WeakAuras mode!"] = true
L["Open Configuration Window"] = true
L["Orbs"] = true
L["Play Warning Sound when about to cap Shadow Orbs."] = true
L["Position"] = true
L["Regulate display visibility with macro conditionals"] = true
L["Reset"] = true
L["Reset Position"] = true
L["Reset to Defaults"] = true
L["Scale"] = true
L["Scanning interval when Aggressive Caching is enabled"] = true
L["Select font for the Complex display"] = true
L["Select font for the Simple display"] = true
L["Set Frame Scale"] = true
L["Set Color 1"] = true
L["Set Color 2"] = true
L["Set Color 3"] = true
L["Set Font Size"] = true
L["Set Frame Height"] = true
L["Set Frame Width"] = true
L["Set Number Spacing"] = true
L["Set Shadow Orb Height"] = true
L["Set Shadow Orb Spacing"] = true
L["Set Shadow Orb Width"] = true
L["Show Orbs out of combat"] = true
L["Shows the frame and toggles it for repositioning."] = true
L["Simple"] = true
L["Simple Display"] = true
L["Sound"] = true
L["Spacing"] = true
L["Text"] = true
L["X Offset"] = true
L["Y Offset"] = true
L["Toggle Lock"] = true
L["Visibility"] = true
L["Warning Sound"] = true
L["WeakAuras"] = true
L["WeakAuras String"] = true
L["WeakAuras String to use when \"WeakAuras\" Display is selected. Copy & paste into WeakAuras to import."] = true
L["Width"] = true
L["Will show Shadow Orbs frame even when not in combat."] = true
L["X offset for the Shadowy Apparition time text"] = true
L["Y offset for the Shadowy Apparition time text"] = true