-- Libraries
local L = LibStub("AceLocale-3.0"):NewLocale("ConspicuousSpirits", "koKR", false)
if not L then return end


-- Translations
L["Aggressive Caching"] = true
L["Aggressive Caching Interval"] = true
L["Color 1"] = "색상 1"
L["Color 2"] = "색상 2"
L["Color 3"] = "색상 3"
L["Complex"] = "복합"
L["Complex Display"] = "복합 디스플레이"
L["Conspicuous Spirits locked!"] = "Conspicuous Spirits 잠금!"
L["Conspicuous Spirits reset!"] = "Conspicuous Spirits 초기화!"
L["Conspicuous Spirits unlocked!"] = "Conspicuous Spirits 잠금해제!"
L["Display"] = "디스플레이"
L["Display Type"] = "디스플레이 형식"
L["Enables frequent distance scanning of all available targets. Will increase CPU usage slightly and is only going to increase accuracy in situations with many fast-moving mobs."] = true
L["File to play."] = "재생할 파일."
L["Font"] = true
L["Font Size"] = "글꼴 크기"
L["Height"] = "높이"
L["IronMaidensShipMessage"] = "주 대포를 쏠 준비를 합니다!"
L["Left mouse button to drag."] = "마우스 왼쪽 버튼으로 드래그하세요."
L["Not possible to unlock in WeakAuras mode!"] = "WeakAuras 모드에서는 잠금해제 할 수 없습니다!"
L["Open Configuration Window"] = "설정 창 열기"
L["Orbs"] = true
L["Play Warning Sound when about to cap Shadow Orbs."] = "어둠의 구슬이 가득 차면 경고 소리 재생하기."
L["Position"] = "위치"
L["Regulate display visibility with macro conditionals"] = true
L["Reset"] = "초기화"
L["Reset Position"] = "위치 초기화"
L["Reset to Defaults"] = "기본으로 초기화"
L["Scale"] = "크기"
L["Scanning interval when Aggressive Caching is enabled"] = true
L["Select font for the Complex display"] = true
L["Select font for the Simple display"] = true
L["Set Color 1"] = "색상 1 설정"
L["Set Color 2"] = "색상 2 설정"
L["Set Color 3"] = "색상 3 설정"
L["Set Font Size"] = "글꼴 크기 설정"
L["Set Frame Height"] = "프레임 높이 설정"
L["Set Frame Scale"] = "프레임 크기 설정"
L["Set Frame Width"] = "프레임 너비 설정"
L["Set Number Spacing"] = "간격 설정"
L["Set Shadow Orb Height"] = "어둠의 구슬 높이 설정"
L["Set Shadow Orb Spacing"] = "어둠의 구슬 간격 설정"
L["Set Shadow Orb Width"] = "어둠의 구슬 너비 설정"
L["Show Orbs out of combat"] = "비 전투 중 어둠의 구슬"
L["Shows the frame and toggles it for repositioning."] = "위치 변경을 위해 프레임을 표시합니다."
L["Simple"] = "심플"
L["Simple Display"] = "심플 디스플레이"
L["Sound"] = "소리"
L["Spacing"] = "간격"
L["Text"] = true
L["Visibility"] = true
L["X Offset"] = true
L["Y Offset"] = true
L["Toggle Lock"] = "잠금 전환"
L["Warning Sound"] = "소리 경고"
L["WeakAuras"] = "WeakAuras"
L["WeakAuras String"] = "WeakAuras 구문"
L["WeakAuras String to use when \"WeakAuras\" Display is selected. Copy & paste into WeakAuras to import."] = "\"WeakAuras\" 디스플레이를 선택했을 때 사용 할 WeakAuras 구문 입니다. WeakAuras의 가져오기에 복사 & 붙여넣기 하세요."
L["Width"] = "너비"
L["Will show Shadow Orbs frame even when not in combat."] = "전투 중이 아닐 때 프레임에 어둠의 구슬이 표시됩니다."
L["X offset for the Shadowy Apparition time text"] = true
L["Y offset for the Shadowy Apparition time text"] = true